name: CloudSim Scheduling Comparison

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Install CloudSim JAR to local Maven repo
      run: |
        mvn install:install-file -Dfile=libs/cloudsim-3.0.3.jar -DgroupId=org.cloudbus.cloudsim -DartifactId=cloudsim -Dversion=3.0.3 -Dpackaging=jar

    - name: Build project with Maven
      run: mvn clean package

    - name: Run simulation
      run: java -cp target/cloudsim-scheduling-comparison-1.0-SNAPSHOT.jar SchedulingAlgorithmComparison

    - name: Save output
      run: |
        mkdir -p simulation-results
        java -cp target/cloudsim-scheduling-comparison-1.0-SNAPSHOT.jar SchedulingAlgorithmComparison > simulation-results/results.txt

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: simulation-results
        path: simulation-results/results.txt
