name: CloudSim Scheduling Comparison (Debug Mode)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: List directory structure (top level)
      run: |
        echo "Project structure:"
        ls -R

    - name: List JAR files in libs
      run: |
        echo "JARs in libs directory:"
        ls -lh libs/

    - name: Check contents of cloudsim-3.0.3.jar
      run: |
        echo "Classes in cloudsim-3.0.3.jar:"
        jar tf libs/cloudsim-3.0.3.jar | grep CloudSim || echo "CloudSim class not found!"

    - name: Compile Java source
      run: |
        mkdir -p target/classes
        javac -cp "libs/*" -d target/classes src/main/java/cloudproject.java

    - name: Show compiled classes
      run: |
        echo "Compiled class files:"
        find target/classes -name "*.class"

    - name: Print full classpath
      run: |
        echo "Full runtime classpath:"
        echo "target/classes:$(echo libs/*.jar | tr ' ' ':')"

    - name: Run simulation with full classpath
      run: |
        CLASSPATH="target/classes:$(echo libs/*.jar | tr ' ' ':')"
        echo "Using classpath: $CLASSPATH"
        java -cp "$CLASSPATH" cloudproject

    - name: Save output to file
      run: |
        mkdir -p simulation-results
        CLASSPATH="target/classes:$(echo libs/*.jar | tr ' ' ':')"
        java -cp "$CLASSPATH" cloudproject > simulation-results/results.txt

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: simulation-results
        path: simulation-results/results.txt
